### PR TITLE
Raise error if config is missing

### LINKED ISSUE #24: Missing guardian_db conf but the error is misleading
Hi

I missed `guardian_db` in config/config.exs and run `mix compile`, got below error:

```
== Compilation error on file lib/guardian_db.ex ==
** (FunctionClauseError) no function clause matching in Keyword.get/3
    (elixir) lib/keyword.ex:150: Keyword.get(nil, :schema_name, nil)
    lib/guardian_db.ex:25: (module)
    lib/guardian_db.ex:18: (module)

could not compile dependency :guardian_db, "mix compile" failed. You can recompile this dependency with "mix deps.compile guardian_db", update it with "mix deps.update guardian_db" or clean it with "mix deps.clean guardian_db"
```

According to [Keyword:get/3](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/keyword.ex#L150), the first arg should be `list` type, however [`Application.get_env(:guardian_db, GuardianDb)`](https://github.com/hassox/guardian_db/blob/master/lib/guardian_db.ex#L25) default value is nil. Further more, I really hope some humanized message like "Application conf guardian_db missed" pop out. 

BR
-Jack

### PR DESCRIPTION
**Pull request by doomspork**
Closes #24

### CODE REVIEW

File: lib/guardian_db.ex [hunk 1]
```diff
@@ -15,19 +15,27 @@ defmodule GuardianDb do
...
 
     use Ecto.Schema
-    @primary_key {:jti, :string, autogenerate: false }
-    @schema_name Keyword.get(Application.get_env(:guardian_db, GuardianDb), :schema_name) || "guardian_tokens"
-    @schema_prefix Keyword.get(Application.get_env(:guardian_db, GuardianDb), :prefix) || nil
-
     import Ecto.Changeset
     import Ecto.Query
 
+    config = Application.get_env(:guardian_db, GuardianDb, [])
```
Comment (doomspork) [inline lib/guardian_db.ex:33]: This is extra.

File: lib/guardian_db.ex [hunk 2]
```diff
@@ -99,19 +105,19 @@ defmodule GuardianDb do
...
+    claims
+    |> Token.find_by_claims
+    |> destroy_token(claims, jwt)
   end
 
-  def repo do
-    Keyword.get(Application.get_env(:guardian_db, GuardianDb), :repo)
+  defp destroy_token(nil, claims, jwt), do: {:ok, {claims, jwt}}
+  defp destroy_token(model, claims, jwt) do
+    case repo().delete(model) do
```
Comment (doomspork) [inline lib/guardian_db.ex:115]: Do we need `repo()` or would `@repo` be sufficient?
